apiVersion: v1
kind: Template
metadata:
  name: saas-usecase-apikey
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "saas-usecase-apikey"
    namespace: ${NAMESPACE}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: saas-usecase-apikey/Jenkinsfile
        env:
          - name: SECRET_NAME
            value: ${SECRET_NAME}
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: TARGET_INSTANCE
            value: ${TARGET_INSTANCE}
          - name: DEVELOPER_ACCOUNT_ID
            value: ${DEVELOPER_ACCOUNT_ID}
          - name: PRIVATE_BASE_URL
            value: ${PRIVATE_BASE_URL}
parameters:
- name: SECRET_NAME
  value: 3scale-toolbox
- name: NAMESPACE
  value: api-lifecycle
- name: TARGET_INSTANCE
  value: 3scale-saas
- name: GIT_REPO
  value: https://github.com/torbjorndahlen/3scale-toolbox-jenkins-samples.git
- name: DEVELOPER_ACCOUNT_ID
  required: true
- name: PRIVATE_BASE_URL
  required: true
