---
swagger: "2.0"
info:
  title: Demo Beer Catalog API
  version: 0.9.19
  description: An API for querying beer catalog of Acme Inc.
  contact:
    name: Laurent Broudoux
    url: http://github.com/torbjorndahlen
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
basePath: /api
paths:
  /beer/{name}:
    get:
      tags:
      - beer
      responses:
        "200":
          description: Beer having requested name
          schema:
            $ref: '#/definitions/Beer'
      operationId: GetBeer
      summary: Get beer having the given name
      description: Get beer having the give name
    parameters:
    - name: name
      description: Name of beer to retrieve
      in: path
      required: true
      type: string
  /beer/findByStatus/{status}:
    get:
      tags:
      - beer
      responses:
        "200":
          description: List of beers having requested status
          schema:
            type: array
            items:
              $ref: '#/definitions/Beer'
      operationId: FindBeersByStatus
      summary: Get beers having status
      description: Get beers having status
    parameters:
    - name: status
      description: Status of beers to retrieve
      in: path
      required: true
      type: string
    - name: page
      description: Number of page to retrieve
      in: query
      type: number
  /beer:
    get:
      tags:
      - beer
      responses:
        "200":
          description: Array of beers
          schema:
            type: array
            items:
              $ref: '#/definitions/Beer'
      operationId: ListBeers
      summary: List beers within catalog
      description: List beers within catalog
    parameters:
    - name: page
      description: Number of pages to retrieve
      in: query
      type: number
definitions:
  Beer:
    properties:
      name:
        description: Name of Beer
        type: string
      country:
        description: Origin country of Beer
        type: string
      type:
        description: Type of Beer
        type: string
      rating:
        description: Rating from customers
        type: number
      status:
        description: Stock status
        type: string
securityDefinitions:
  api-key:
    type: apiKey
    name: api-key
    in: header
security:
- api-key: []
tags:
- name: beer
  description: Beer resource
